name: Test and deploy on target

on:
  push:
    branches:
      - main
  pull_request:
    branches:

jobs:
  build:
    name: "Test and deploy on c4dtsrv1"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run `prettier`
        uses: actionsx/prettier@v2
        with:
          args: --check .

      - name: Test
        uses: fylein/python-pytest-github-action@v2
        with:
          args: pip3 install -r requirements.txt && pytest

      - name: Deploy
        if: github.event_name == 'push'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H c4dtsrv1.epfl.ch > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh factory@c4dtsrv1.epfl.ch mkdir -p bin && scp update.sh factory@c4dtsrv1.epfl.ch:bin/ && ssh factory@c4dtsrv1.epfl.ch bin/update.sh
